import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Alert, Button, Card, Col, Form, Input, List, Modal, Popconfirm, Row, Space, Statistic, Switch, Table, Tag, Typography, Upload, message } from 'antd'
import { ArrowLeftOutlined, DeleteOutlined, FileTextOutlined, InboxOutlined, SaveOutlined } from '@ant-design/icons'
import type { UploadProps } from 'antd'
import { api } from '@/services/api'

const { Title, Text } = Typography
const { Dragger } = Upload
interface KB { id: number; name: string; description: string | null; document_count: number; chunk_count: number; total_size_bytes: number; is_active: boolean; index_status?: string; embedding_model?: string }
interface Doc { id: number; filename: string; file_type: string; file_size: number; status: string; chunk_count: number; error_message?: string; duplicate?: boolean; parse_time_ms?: number; split_time_ms?: number; embedding_time_ms?: number; total_time_ms?: number; processing_stage?: string; failed_stage?: string; processing_attempts?: number }
interface ImportJob { id: string; status: string; total: number; processed: number; imported: number; duplicate: number; error_message?: string; logs: Array<{ name: string; status: string; message?: string }> }
const states: Record<string, { color: string; text: string }> = {
  pending: { color: 'default', text: '等待/重试中' }, processing: { color: 'processing', text: '处理中' }, completed: { color: 'success', text: '已入库' }, error: { color: 'error', text: '处理失败' }, cleanup_pending: { color: 'warning', text: '待清理' },
}
const stageNames: Record<string, string> = { preparing: '准备任务', parsing: '解析文档', splitting: '切分文本', indexing: '向量化与写入', cleanup: '清理向量', completed: '完成' }
const duration = (ms?: number) => ms ? `${(ms / 1000).toFixed(ms > 10000 ? 1 : 2)} 秒` : '—'

export default function KnowledgeDetail() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate()
  const [kb, setKb] = useState<KB | null>(null); const [docs, setDocs] = useState<Doc[]>([]); const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const [rebuilding, setRebuilding] = useState(false); const [editing, setEditing] = useState(false); const [feishuOpen, setFeishuOpen] = useState(false); const [feishuImporting, setFeishuImporting] = useState(false); const [importJob, setImportJob] = useState<ImportJob | null>(null); const [form] = Form.useForm(); const [feishuForm] = Form.useForm()
  const load = useCallback(async (showLoading = true) => { if (!id) return; if (showLoading) setLoading(true); try { const [base, documentList] = await Promise.all([api.get<KB>(`/knowledge/bases/${id}`), api.get<{ items: Doc[] }>(`/knowledge/documents?kb_id=${id}`)]); setKb(base); setDocs(documentList.items || []) } catch (error: any) { if (error?.response?.status !== 429) message.error('加载知识库详情失败') } finally { if (showLoading) setLoading(false) } }, [id])
  useEffect(() => { load() }, [load])
  const active = docs.some(d => ['pending', 'processing', 'cleanup_pending'].includes(d.status))
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => load(false), 8000); return () => window.clearInterval(timer) }, [active, load])
  useEffect(() => { if (!importJob || !['pending', 'processing'].includes(importJob.status)) return; const timer = window.setInterval(async () => { try { const job = await api.get<ImportJob>(`/knowledge/feishu/imports/${importJob.id}`); setImportJob(job); if (job.status === 'completed') { message.success(`飞书导入完成：新增 ${job.imported} 篇，重复跳过 ${job.duplicate} 篇`); load(false) } } catch { /* 导入任务的下一次刷新会重试 */ } }, 1000); return () => window.clearInterval(timer) }, [importJob?.id, importJob?.status, load])
  const upload: UploadProps['customRequest'] = async ({ file, onSuccess, onError }: any) => { setUploading(true); try { const body = new FormData(); body.append('file', file); const document = await api.post<Doc>(`/knowledge/bases/${id}/upload`, body, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 120000 }); message.info(document.duplicate ? `${file.name} 已存在，未重复入库` : `${file.name} 已接收，正在后台处理`); onSuccess?.({}, file); load() } catch (error) { message.error(`${file.name} 上传失败`); onError?.(error) } finally { setUploading(false) } }
  const save = async () => { const values = await form.validateFields(); await api.put(`/knowledge/bases/${id}`, values); setEditing(false); message.success('知识库已更新'); load() }
  const rebuildIndex = async () => { setRebuilding(true); try { const result = await api.post<{ document_count: number; message: string }>(`/knowledge/bases/${id}/rebuild-index`); message.success(`${result.message}（${result.document_count} 篇文档）`); load() } catch (error: any) { message.error(error?.response?.data?.detail || '启动索引重建失败') } finally { setRebuilding(false) } }
  const clearFailedDocuments = async () => { try { const result = await api.delete<{ removed: number; retained: Array<{ filename: string }> }>(`/knowledge/bases/${id}/failed-documents`); result.retained.length ? message.warning(`已清除 ${result.removed} 条，${result.retained.length} 条残留待重试`) : message.success(`已清除 ${result.removed} 条失败记录`); load() } catch (error: any) { message.error(error?.response?.data?.detail || '清除失败记录失败') } }
  const importFeishu = async () => { const values = await feishuForm.validateFields(); setFeishuImporting(true); try { const result = await api.post<{ job_id: string; status: string }>(`/knowledge/bases/${id}/feishu/import`, values); setImportJob({ id: result.job_id, status: result.status, total: 0, processed: 0, imported: 0, duplicate: 0, logs: [] }); setFeishuOpen(false); feishuForm.resetFields(); message.success('已开始后台导入，可在下方查看实时进度') } catch (error: any) { message.error(error?.response?.data?.detail || '飞书导入失败') } finally { setFeishuImporting(false) } }
  const removeDoc = async (docId: number) => { try { await api.delete(`/knowledge/documents/${docId}`); message.success('文档及向量已删除') } catch { message.warning('向量清理尚未完成，已保留为待清理状态；请稍后重试删除') } finally { load() } }
  if (!kb) return <Card loading />
  const columns = [
    { title: '文档与任务', dataIndex: 'filename', render: (name: string, d: Doc) => <div><Text strong>{name}</Text><span className="task-detail">{d.processing_stage && `阶段：${stageNames[d.processing_stage] || d.processing_stage}`} · 尝试 {d.processing_attempts || 0} 次 · 总耗时 {duration(d.total_time_ms)}</span>{d.error_message && <Text type="danger" className="task-detail">{d.error_message}</Text>}</div> },
    { title: '类型', dataIndex: 'file_type', width: 90, render: (v: string) => <Tag>{v.toUpperCase()}</Tag> },
    { title: '状态', dataIndex: 'status', width: 110, render: (v: string) => <Tag color={(states[v] || {}).color}>{(states[v] || { text: v }).text}</Tag> },
    { title: '耗时', width: 155, render: (_: unknown, d: Doc) => <Text type="secondary">解析 {duration(d.parse_time_ms)}<br />切分 {duration(d.split_time_ms)} · 向量 {duration(d.embedding_time_ms)}</Text> },
    { title: '切片', dataIndex: 'chunk_count', width: 75 },
    { title: '操作', width: 96, render: (_: unknown, d: Doc) => <Popconfirm title={d.status === 'cleanup_pending' ? '再次尝试清理向量？' : '确认删除此文档及其向量？'} onConfirm={() => removeDoc(d.id)}><Button type="link" danger icon={<DeleteOutlined />}>{d.status === 'cleanup_pending' ? '重试清理' : '删除'}</Button></Popconfirm> },
  ]
  return <div>
    <div className="knowledge-hero"><Space><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/knowledge')}>知识库</Button><div><Title level={3} style={{ margin: 0 }}>{kb.name}</Title><Text type="secondary">{kb.description || '集中管理可检索的业务资料'}</Text></div></Space><Button icon={<SaveOutlined />} onClick={() => { form.setFieldsValue(kb); setEditing(true) }}>编辑</Button></div>
    <Row gutter={[16, 16]} style={{ marginBottom: 20 }}><Col xs={24} md={8}><Card><Statistic title="文档" value={kb.document_count} prefix={<FileTextOutlined />} /></Card></Col><Col xs={24} md={8}><Card><Statistic title="知识切片" value={kb.chunk_count} /></Card></Col><Col xs={24} md={8}><Card><Statistic title="存储占用" value={(kb.total_size_bytes / 1024 / 1024).toFixed(1)} suffix="MB" /></Card></Col></Row>
    <Card title="添加资料" style={{ marginBottom: 20 }} extra={<Space><Button onClick={() => setFeishuOpen(true)}>导入飞书文档</Button>{kb.index_status === 'rebuild_required' && <Popconfirm title="重建会清空该知识库的旧向量并重新向量化所有已完成与待处理文档。已先创建本地备份，确认继续？" onConfirm={rebuildIndex}><Button type="primary" loading={rebuilding}>重建索引</Button></Popconfirm>}</Space>}>{kb.index_status === 'rebuild_required' && <Alert style={{ marginBottom: 14 }} type="warning" showIcon message="索引需要重建" description="当前向量配置与已有索引不一致。重建会创建本地备份，再按当前向量模型重新入库。" />}<Dragger multiple disabled={uploading || kb.index_status === 'rebuild_required'} customRequest={upload} accept=".pdf,.docx,.xlsx,.txt,.md,.csv,.json"><p className="ant-upload-drag-icon"><InboxOutlined /></p><p>{uploading ? '正在上传…' : '拖入文件，或点击选择文件'}</p><Text type="secondary">文件在后台处理，不会阻塞当前页面。支持失败后自动重试。</Text></Dragger>{active && <Alert style={{ marginTop: 14 }} type="info" showIcon message="后台任务正在执行" description="页面会自动刷新进度；每个文档会展示当前阶段、重试次数和耗时。" />}</Card>
    {importJob && <Card title="飞书导入进度" style={{ marginBottom: 20 }} extra={<Tag color={importJob.status === 'completed' ? 'success' : importJob.status === 'failed' ? 'error' : 'processing'}>{importJob.status === 'completed' ? '已完成' : importJob.status === 'failed' ? '失败' : '导入中'}</Tag>}><Text type="secondary">已处理 {importJob.processed} / {importJob.total || '读取中'}，新增 {importJob.imported}，重复跳过 {importJob.duplicate}</Text>{importJob.error_message && <Alert type="error" showIcon message="导入失败" description={importJob.error_message} style={{ marginTop: 12 }} />}<List size="small" style={{ marginTop: 12 }} dataSource={[...importJob.logs].reverse()} locale={{ emptyText: '正在读取 Wiki 目录…' }} renderItem={item => <List.Item><Space><Tag color={item.status === '失败' ? 'error' : item.status === '重复跳过' ? 'default' : 'processing'}>{item.status}</Tag><Text>{item.name}</Text>{item.message && <Text type="secondary">{item.message}</Text>}</Space></List.Item>} /></Card>}
    <Card title="资料处理记录" extra={<Space>{docs.some(doc => ['error', 'failed'].includes(doc.status)) && <Popconfirm title="清除全部失败记录？会删除对应的数据库记录和残留向量，原始上传文件不会删除。" onConfirm={clearFailedDocuments}><Button danger>清除失败记录</Button></Popconfirm>}<Button onClick={() => load()}>刷新</Button></Space>}><Table rowKey="id" loading={loading} columns={columns} dataSource={docs} pagination={{ pageSize: 10 }} scroll={{ x: 780 }} /></Card>
    <Modal title="编辑知识库" open={editing} onCancel={() => setEditing(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="description" label="描述"><Input.TextArea rows={3} /></Form.Item><Form.Item name="is_active" valuePropName="checked" label="启用"><Switch /></Form.Item></Form></Modal>
    <Modal title="导入飞书资料" open={feishuOpen} onCancel={() => setFeishuOpen(false)} onOk={importFeishu} confirmLoading={feishuImporting} okText="开始导入"><Alert type="info" showIcon message="支持单篇 Docx 或 Wiki 节点链接" description={<>应用会遍历 Wiki 的分页节点。请先在 <Link to="/settings/sources">设置 › 数据源</Link> 保存并测试应用凭据。</>} style={{ marginBottom: 16 }} /><Form form={feishuForm} layout="vertical"><Form.Item name="url" label="飞书链接" rules={[{ required: true, type: 'url', message: '请输入有效的 https 链接' }]}><Input placeholder="https://xxx.feishu.cn/docx/... 或 /wiki/..." /></Form.Item><Form.Item name="max_nodes" label="Wiki 最多导入节点数" initialValue={500} extra="默认 500，单次最多 1000；节点过多建议分目录导入。"><Input type="number" min={1} max={1000} /></Form.Item></Form></Modal>
  </div>
}
