import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Button, Card, Col, Form, Input, Modal, Popconfirm, Row, Space, Statistic, Switch, Table, Tag, Typography, Upload, message } from 'antd'
import { ArrowLeftOutlined, DeleteOutlined, FileTextOutlined, InboxOutlined, SaveOutlined } from '@ant-design/icons'
import type { UploadProps } from 'antd'
import { api } from '@/services/api'

const { Title, Text } = Typography
const { Dragger } = Upload
interface KB { id: number; name: string; description: string | null; document_count: number; chunk_count: number; total_size_bytes: number; is_active: boolean }
interface Doc { id: number; filename: string; file_type: string; file_size: number; status: string; chunk_count: number; error_message?: string; duplicate?: boolean }
const status: Record<string, { color: string; text: string }> = { pending: { color: 'default', text: '等待中' }, processing: { color: 'processing', text: '处理中' }, completed: { color: 'success', text: '已解析' }, error: { color: 'error', text: '失败' } }
export default function KnowledgeDetail() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const [kb, setKb] = useState<KB | null>(null); const [docs, setDocs] = useState<Doc[]>([]); const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const [editing, setEditing] = useState(false); const [form] = Form.useForm()
  const load = useCallback(async (showLoading = true) => { if (!id) return; if (showLoading) setLoading(true); try { const [base, documentList] = await Promise.all([api.get<KB>(`/knowledge/bases/${id}`), api.get<{ items: Doc[] }>(`/knowledge/documents?kb_id=${id}`)]); setKb(base); setDocs(documentList.items || []) } catch { message.error('加载知识库详情失败') } finally { if (showLoading) setLoading(false) } }, [id])
  useEffect(() => { load() }, [load])
  const hasProcessing = docs.some((doc) => doc.status === 'pending' || doc.status === 'processing')
  useEffect(() => { if (!hasProcessing) return; const timer = window.setInterval(() => { load(false) }, 2500); return () => window.clearInterval(timer) }, [hasProcessing, load])
  const upload: UploadProps['customRequest'] = async ({ file, onSuccess, onError }: any) => { setUploading(true); try { const body = new FormData(); body.append('file', file); const document = await api.post<Doc>(`/knowledge/bases/${id}/upload`, body, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 120000 }); message.info(document.duplicate ? `${file.name} 已存在，未重复入库` : `${file.name} 已接收，正在后台解析`); onSuccess?.({}, file); load() } catch (error) { message.error(`${file.name} 上传失败`); onError?.(error) } finally { setUploading(false) } }
  const save = async () => { const values = await form.validateFields(); await api.put(`/knowledge/bases/${id}`, values); setEditing(false); message.success('知识库已更新'); load() }
  const removeDoc = async (docId: number) => { await api.delete(`/knowledge/documents/${docId}`); message.success('文档已删除'); load() }
  if (!kb) return <Card loading />
  const columns = [{ title: '文档', dataIndex: 'filename', render: (name: string, d: Doc) => <div><Text strong>{name}</Text>{d.error_message && <><br /><Text type="danger">{d.error_message}</Text></>}</div> }, { title: '类型', dataIndex: 'file_type', width: 90, render: (v: string) => <Tag>{v.toUpperCase()}</Tag> }, { title: '状态', dataIndex: 'status', width: 100, render: (v: string) => <Tag color={(status[v] || {}).color}>{(status[v] || { text: v }).text}</Tag> }, { title: '切片', dataIndex: 'chunk_count', width: 80 }, { title: '操作', width: 100, render: (_: unknown, d: Doc) => <Popconfirm title="确认删除此文档？" onConfirm={() => removeDoc(d.id)}><Button type="link" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm> }]
  return <div><Space style={{ marginBottom: 20 }}><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/knowledge')}>知识库列表</Button><Title level={3} style={{ margin: 0 }}>{kb.name}</Title></Space><Row gutter={16} style={{ marginBottom: 18 }}><Col span={8}><Card><Statistic title="文档" value={kb.document_count} prefix={<FileTextOutlined />} /></Card></Col><Col span={8}><Card><Statistic title="知识切片" value={kb.chunk_count} /></Card></Col><Col span={8}><Card><Statistic title="存储占用" value={(kb.total_size_bytes / 1024 / 1024).toFixed(1)} suffix="MB" /></Card></Col></Row><Card title="上传文档" style={{ marginBottom: 18 }}><Dragger multiple disabled={uploading} customRequest={upload} accept=".pdf,.docx,.xlsx,.txt,.md,.csv,.json"><p className="ant-upload-drag-icon"><InboxOutlined /></p><p>{uploading ? '正在上传…' : '点击或拖拽文件上传'}</p><Text type="secondary">文件接收后将在后台解析；页面可继续使用。</Text></Dragger>{hasProcessing && <Text type="secondary" style={{ display: 'block', marginTop: 12 }}>后台正在解析文档，列表会自动刷新。</Text>}</Card><Card title="文档列表" extra={<Button onClick={() => load()}>刷新</Button>}><Table rowKey="id" loading={loading} columns={columns} dataSource={docs} pagination={{ pageSize: 10 }} /></Card><Button style={{ marginTop: 16 }} icon={<SaveOutlined />} onClick={() => { form.setFieldsValue(kb); setEditing(true) }}>编辑知识库</Button><Modal title="编辑知识库" open={editing} onCancel={() => setEditing(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="description" label="描述"><Input.TextArea rows={3} /></Form.Item><Form.Item name="is_active" valuePropName="checked" label="启用"><Switch /></Form.Item></Form></Modal></div>
}
