import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, Button, Card, Col, Form, Input, Modal, Popconfirm, Row, Space, Statistic, Switch, Table, Tag, Typography, Upload, message } from 'antd'
import { ArrowLeftOutlined, CloudOutlined, DeleteOutlined, FileTextOutlined, InboxOutlined, SaveOutlined } from '@ant-design/icons'
import type { UploadProps } from 'antd'
import { api } from '@/services/api'

const { Title, Text } = Typography
const { Dragger } = Upload
interface KB { id: number; name: string; description: string | null; document_count: number; chunk_count: number; total_size_bytes: number; is_active: boolean; index_status?: string; embedding_model?: string }
interface Doc { id: number; filename: string; file_type: string; file_size: number; status: string; chunk_count: number; error_message?: string; duplicate?: boolean; parse_time_ms?: number; split_time_ms?: number; embedding_time_ms?: number; total_time_ms?: number; processing_stage?: string; failed_stage?: string; processing_attempts?: number }
interface WebPreview { title: string; url: string; content_preview: string; content_length: number }
const states: Record<string, { color: string; text: string }> = {
  pending: { color: 'default', text: '等待/重试中' }, processing: { color: 'processing', text: '处理中' }, completed: { color: 'success', text: '已入库' }, error: { color: 'error', text: '处理失败' }, cleanup_pending: { color: 'warning', text: '待清理' },
}
const stageNames: Record<string, string> = { preparing: '准备任务', parsing: '解析文档', splitting: '切分文本', indexing: '向量化与写入', cleanup: '清理向量', completed: '完成' }
const duration = (ms?: number) => ms ? `${(ms / 1000).toFixed(ms > 10000 ? 1 : 2)} 秒` : '—'

export default function KnowledgeDetail() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate()
  const [kb, setKb] = useState<KB | null>(null); const [docs, setDocs] = useState<Doc[]>([]); const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const [rebuilding, setRebuilding] = useState(false); const [editing, setEditing] = useState(false); const [webOpen, setWebOpen] = useState(false); const [cloudOpen, setCloudOpen] = useState(false); const [cloudImporting, setCloudImporting] = useState(false); const [webPreviewing, setWebPreviewing] = useState(false); const [webImporting, setWebImporting] = useState(false); const [webPreview, setWebPreview] = useState<WebPreview | null>(null); const [form] = Form.useForm(); const [webForm] = Form.useForm(); const [cloudForm] = Form.useForm()
  const load = useCallback(async (showLoading = true) => { if (!id) return; if (showLoading) setLoading(true); try { const [base, documentList] = await Promise.all([api.get<KB>(`/knowledge/bases/${id}`), api.get<{ items: Doc[] }>(`/knowledge/documents?kb_id=${id}`)]); setKb(base); setDocs(documentList.items || []) } catch (error: any) { if (error?.response?.status !== 429) message.error('加载知识库详情失败') } finally { if (showLoading) setLoading(false) } }, [id])
  useEffect(() => { load() }, [load])
  const active = docs.some(d => ['pending', 'processing', 'cleanup_pending'].includes(d.status))
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => load(false), 8000); return () => window.clearInterval(timer) }, [active, load])
  const upload: UploadProps['customRequest'] = async ({ file, onSuccess, onError }: any) => { setUploading(true); try { const body = new FormData(); body.append('file', file); const document = await api.post<Doc>(`/knowledge/bases/${id}/upload`, body, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 120000 }); message.info(document.duplicate ? `${file.name} 已存在，未重复入库` : `${file.name} 已接收，正在后台处理`); onSuccess?.({}, file); load() } catch (error) { message.error(`${file.name} 上传失败`); onError?.(error) } finally { setUploading(false) } }
  const save = async () => { const values = await form.validateFields(); await api.put(`/knowledge/bases/${id}`, values); setEditing(false); message.success('知识库已更新'); load() }
  const rebuildIndex = async () => { setRebuilding(true); try { const result = await api.post<{ document_count: number; message: string }>(`/knowledge/bases/${id}/rebuild-index`); message.success(`${result.message}（${result.document_count} 篇文档）`); load() } catch (error: any) { message.error(error?.response?.data?.detail || '启动索引重建失败') } finally { setRebuilding(false) } }
  const clearFailedDocuments = async () => { try { const result = await api.delete<{ removed: number; retained: Array<{ filename: string }> }>(`/knowledge/bases/${id}/failed-documents`); result.retained.length ? message.warning(`已清除 ${result.removed} 条，${result.retained.length} 条残留待重试`) : message.success(`已清除 ${result.removed} 条失败记录`); load() } catch (error: any) { message.error(error?.response?.data?.detail || '清除失败记录失败') } }
  const previewWebUrl = async () => { const values = await webForm.validateFields(); setWebPreviewing(true); try { setWebPreview(await api.post<WebPreview>(`/knowledge/bases/${id}/web/preview`, values)) } catch (error: any) { message.error(error?.response?.data?.detail || '网页预览失败'); setWebPreview(null) } finally { setWebPreviewing(false) } }
  const importWebUrl = async () => { const values = await webForm.validateFields(); setWebImporting(true); try { const result = await api.post<{ document: Doc; duplicate: boolean }>(`/knowledge/bases/${id}/web/import`, values); message.success(result.duplicate ? '该网页内容已存在，未重复入库' : '网页已提交，正在后台处理'); setWebOpen(false); setWebPreview(null); webForm.resetFields(); load() } catch (error: any) { message.error(error?.response?.data?.detail || '网页导入失败') } finally { setWebImporting(false) } }
  const importCloudDocs = async () => { const values = await cloudForm.validateFields(); setCloudImporting(true); try { await api.post(`/knowledge/bases/${id}/feishu/import`, values); message.success('云文档导入任务已启动'); setCloudOpen(false); cloudForm.resetFields() } catch (error: any) { message.error(error?.response?.data?.detail || '云文档导入失败') } finally { setCloudImporting(false) } }
  const removeDoc = async (docId: number) => { try { await api.delete(`/knowledge/documents/${docId}`); message.success('文档及向量已删除') } catch { message.warning('向量清理尚未完成，已保留为待清理状态；请稍后重试删除') } finally { load() } }
  if (!kb) return <Card loading />
  const columns = [
    { title: '文档与任务', dataIndex: 'filename', render: (name: string, d: Doc) => <div><Text strong>{name}</Text><span className="task-detail">{d.processing_stage && `阶段：${stageNames[d.processing_stage] || d.processing_stage}`} · 尝试 {d.processing_attempts || 0} 次 · 总耗时 {duration(d.total_time_ms)}</span>{d.error_message && <Text type="danger" className="task-detail">{d.error_message}</Text>}</div> },
    { title: '类型', dataIndex: 'file_type', width: 90, render: (v: string) => <Tag>{v.toUpperCase()}</Tag> },
    { title: '状态', dataIndex: 'status', width: 110, render: (v: string) => <Tag color={(states[v] || {}).color}>{(states[v] || { text: v }).text}</Tag> },
    { title: '耗时', width: 155, render: (_: unknown, d: Doc) => <Text type="secondary">解析 {duration(d.parse_time_ms)}<br />切分 {duration(d.split_time_ms)} · 向量 {duration(d.embedding_time_ms)}</Text> },
    { title: '切片', dataIndex: 'chunk_count', width: 75 },
    { title: '操作', width: 96, render: (_: unknown, d: Doc) => <Popconfirm title={d.status === 'cleanup_pending' ? '再次尝试清理向量？' : '确认删除此文档及其向量？'} onConfirm={() => removeDoc(d.id)}><Button type="link" danger icon={<DeleteOutlined />}>{d.status === 'cleanup_pending' ? '重试清理' : '删除'}</Button></Popconfirm> },
  ]
  return <div>
    <div className="knowledge-hero"><Space><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/knowledge')}>知识库</Button><div><Title level={3} style={{ margin: 0 }}>{kb.name}</Title><Text type="secondary">{kb.description || '集中管理可检索的业务资料'}</Text></div></Space><Button icon={<SaveOutlined />} onClick={() => { form.setFieldsValue(kb); setEditing(true) }}>编辑</Button></div>
    <Row gutter={[16, 16]} style={{ marginBottom: 20 }}><Col xs={24} md={8}><Card><Statistic title="文档" value={kb.document_count} prefix={<FileTextOutlined />} /></Card></Col><Col xs={24} md={8}><Card><Statistic title="知识切片" value={kb.chunk_count} /></Card></Col><Col xs={24} md={8}><Card><Statistic title="存储占用" value={(kb.total_size_bytes / 1024 / 1024).toFixed(1)} suffix="MB" /></Card></Col></Row>
    <Card title="导入资料" style={{ marginBottom: 20 }} extra={kb.index_status === 'rebuild_required' && <Popconfirm title="重建会清空该知识库的旧向量并重新向量化所有已完成与待处理文档。已先创建本地备份，确认继续？" onConfirm={rebuildIndex}><Button type="primary" loading={rebuilding}>重建索引</Button></Popconfirm>}>
      {kb.index_status === 'rebuild_required' && <Alert style={{ marginBottom: 14 }} type="warning" showIcon message="索引需要重建" description="当前向量配置与已有索引不一致。重建会创建本地备份，再按当前向量模型重新入库。" />}
      <Row gutter={[16, 16]}>
        <Col xs={24} md={8}><Card size="small" title="文件"><Dragger multiple disabled={uploading || kb.index_status === 'rebuild_required'} customRequest={upload} accept=".pdf,.docx,.xlsx,.txt,.md,.csv,.json"><p className="ant-upload-drag-icon"><InboxOutlined /></p><p>{uploading ? '正在上传…' : '拖入文件，或点击选择文件'}</p><Text type="secondary">从本机导入并后台处理。</Text></Dragger></Card></Col>
        <Col xs={24} md={8}><Card size="small" title="云文档"><button type="button" disabled={kb.index_status === 'rebuild_required'} onClick={() => setCloudOpen(true)} style={{ width: '100%', height: 135, border: '1px dashed #b8c5d9', borderRadius: 8, background: '#fafcff', cursor: kb.index_status === 'rebuild_required' ? 'not-allowed' : 'pointer', color: '#1f2937' }}><CloudOutlined style={{ display: 'block', color: '#1677ff', fontSize: 24, margin: '0 auto 8px' }} /><span style={{ display: 'block', fontSize: 16, lineHeight: 1.35, marginBottom: 7 }}>从云文档导入</span><span style={{ display: 'block', color: '#64748b', fontSize: 12, fontWeight: 400 }}>支持已授权的飞书文档与知识库</span></button></Card></Col>
        <Col xs={24} md={8}><Card size="small" title="网页"><button type="button" disabled={kb.index_status === 'rebuild_required'} onClick={() => setWebOpen(true)} style={{ width: '100%', height: 135, border: '1px dashed #b8c5d9', borderRadius: 8, background: '#fafcff', cursor: kb.index_status === 'rebuild_required' ? 'not-allowed' : 'pointer', color: '#1f2937' }}><CloudOutlined style={{ display: 'block', color: '#1677ff', fontSize: 24, margin: '0 auto 8px' }} /><span style={{ display: 'block', fontSize: 16, lineHeight: 1.35, marginBottom: 7 }}>从网页链接导入</span><span style={{ display: 'block', color: '#64748b', fontSize: 12, fontWeight: 400 }}>仅支持公开 HTML 页面</span></button></Card></Col>
      </Row>
      {active && <Alert style={{ marginTop: 14 }} type="info" showIcon message="后台任务正在执行" description="页面会自动刷新进度；每个文档会展示当前阶段、重试次数和耗时。" />}
    </Card>
    <Card title="资料处理记录" extra={<Space>{docs.some(doc => ['error', 'failed'].includes(doc.status)) && <Popconfirm title="清除全部失败记录？会删除对应的数据库记录和残留向量，原始上传文件不会删除。" onConfirm={clearFailedDocuments}><Button danger>清除失败记录</Button></Popconfirm>}<Button onClick={() => load()}>刷新</Button></Space>}><Table rowKey="id" loading={loading} columns={columns} dataSource={docs} pagination={{ pageSize: 10 }} scroll={{ x: 780 }} /></Card>
    <Modal title="编辑知识库" open={editing} onCancel={() => setEditing(false)} onOk={save}><Form form={form} layout="vertical"><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="description" label="描述"><Input.TextArea rows={3} /></Form.Item><Form.Item name="is_active" valuePropName="checked" label="启用"><Switch /></Form.Item></Form></Modal>
    <Modal title="从网页链接导入" open={webOpen} onCancel={() => { setWebOpen(false); setWebPreview(null) }} onOk={importWebUrl} confirmLoading={webImporting} okText="确认导入" okButtonProps={{ disabled: !webPreview }}><Alert type="info" showIcon message="仅导入公开 HTML 网页" description="系统不会携带 Cookie 或访问内网地址。请先预览正文，确认后才会写入知识库。" style={{ marginBottom: 16 }} /><Form form={webForm} layout="vertical"><Form.Item name="url" label="网页链接" rules={[{ required: true, type: 'url', message: '请输入有效的 http/https 链接' }]}><Input placeholder="https://example.com/article" onChange={() => setWebPreview(null)} /></Form.Item><Button onClick={previewWebUrl} loading={webPreviewing}>预览正文</Button></Form>{webPreview && <Card size="small" title={webPreview.title} style={{ marginTop: 16 }}><Text type="secondary">{webPreview.url} · 已提取 {webPreview.content_length} 字</Text><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 260, overflow: 'auto', marginTop: 12, fontFamily: 'inherit' }}>{webPreview.content_preview}</pre></Card>}</Modal>
    <Modal title="从云文档导入" open={cloudOpen} onCancel={() => setCloudOpen(false)} onOk={importCloudDocs} confirmLoading={cloudImporting} okText="开始导入"><Alert type="info" showIcon message="请先在云文档配置中启用数据源" description="支持飞书 Docx 文档和知识库链接。导入在后台执行，窗口会立即关闭。" style={{ marginBottom: 16 }} /><Form form={cloudForm} layout="vertical" initialValues={{ max_nodes: 500 }}><Form.Item name="url" label="云文档链接" rules={[{ required: true, type: 'url', message: '请输入有效链接' }]}><Input placeholder="https://xxx.feishu.cn/docx/... 或 /wiki/..." /></Form.Item><Form.Item name="max_nodes" label="知识库最多导入节点数" extra="单篇文档填写 1；知识库链接可按需要调整。"><Input type="number" min={1} max={1000} /></Form.Item></Form></Modal>
  </div>
}
